### ISSUE TITLE
GPS variable conversion

### ISSUE THREAD

**Issue by BThunderman** [ricaun/esp32-ttnmapper-gps#3]
Hi, thank you for this project. It helped me alot for sending gps with lora packets.
If have a question about the conversion of the gps longitude and latitude (in lmic_payload.ino, line 22f). I haven't understood why the values are converted this way with adding 90, dividing by 180, multiplying with 16777215 (2^24). Can you please explain why this is done? I also saw other people do it, but there are always no comments at this code.
Thanks!

**Comment by ricaun** [comment]
It's a float to 3 bytes conversion, the original example from ttnmapper uses this algorithm.

**Comment by BThunderman** [comment]
Thank you!
